// AUTO-GENERATED by scripts/gen-bundles.mjs — do not edit.
// Re-run with `npm run gen-bundles` after adding/removing JSON content.

import type { Weapon } from '../core/state/GameState';
import type { UnitTemplate } from './loader';
import type { MapDef } from '../core/setup/types';
import type { MissionDef } from '../missions/types';
import type { Faction } from './loader';

import weapons_blade from './weapons/blade.json';
import weapons_heavy_rifle from './weapons/heavy_rifle.json';
import weapons_rifle from './weapons/rifle.json';
import weapons_rpg from './weapons/rpg.json';
import weapons_smg from './weapons/smg.json';
import units_Blue_Squadee from './units/Blue_Squadee.json';
import units_Blue_squad_leader from './units/Blue_squad_leader.json';
import units_conscript from './units/conscript.json';
import units_elite from './units/elite.json';
import units_heavy_gunner from './units/heavy_gunner.json';
import units_squad_lead from './units/squad_lead.json';
import units_trooper from './units/trooper.json';
import units_veteran from './units/veteran.json';
import maps_demo from './maps/demo.json';
import maps_testmap1 from './maps/testmap1.json';
import missions_breakthrough from './missions/breakthrough.json';
import missions_decapitation from './missions/decapitation.json';
import missions_extraction from './missions/extraction.json';
import missions_holdout from './missions/holdout.json';
import missions_last_stand from './missions/last-stand.json';
import missions_night_extraction from './missions/night-extraction.json';
import missions_reconnaissance from './missions/reconnaissance.json';
import factions_Blue from './factions/Blue.json';
import factions_Red from './factions/Red.json';
import factions_neutral from './factions/neutral.json';

export const BUNDLED_WEAPONS: ReadonlyArray<Weapon> = [
  weapons_blade as unknown as Weapon,
  weapons_heavy_rifle as unknown as Weapon,
  weapons_rifle as unknown as Weapon,
  weapons_rpg as unknown as Weapon,
  weapons_smg as unknown as Weapon,
];
export const BUNDLED_TEMPLATES: ReadonlyArray<UnitTemplate> = [
  units_Blue_Squadee as unknown as UnitTemplate,
  units_Blue_squad_leader as unknown as UnitTemplate,
  units_conscript as unknown as UnitTemplate,
  units_elite as unknown as UnitTemplate,
  units_heavy_gunner as unknown as UnitTemplate,
  units_squad_lead as unknown as UnitTemplate,
  units_trooper as unknown as UnitTemplate,
  units_veteran as unknown as UnitTemplate,
];
export const BUNDLED_MAPS: ReadonlyArray<MapDef> = [
  maps_demo as unknown as MapDef,
  maps_testmap1 as unknown as MapDef,
];
export const BUNDLED_MISSIONS: ReadonlyArray<MissionDef> = [
  missions_breakthrough as unknown as MissionDef,
  missions_decapitation as unknown as MissionDef,
  missions_extraction as unknown as MissionDef,
  missions_holdout as unknown as MissionDef,
  missions_last_stand as unknown as MissionDef,
  missions_night_extraction as unknown as MissionDef,
  missions_reconnaissance as unknown as MissionDef,
];
export const BUNDLED_FACTIONS: ReadonlyArray<Faction> = [
  factions_Blue as unknown as Faction,
  factions_Red as unknown as Faction,
  factions_neutral as unknown as Faction,
];
